### ISSUE TITLE
C stops playing

### ISSUE THREAD

**Issue by ssj71** [fps/asciichanges#1]
Fun little project here. I just started tinkering and found I can't get the web player to play a regular C chord like `| C |`. It parses fine it just doesn't play. Jazzier chords work, so `| Cmaj7 | C | Gmaj7 |` will play the first bar, then go silent on the 2nd and never play the 3rd bar. Maybe I just need some documentation on what chords are supported and what the expected syntax is?

**Comment by fps** [comment]
Hey, thanks for the report. It was a stupid little mistake.. Should work now :) Fixed in https://github.com/fps/asciichanges/commit/9310f2d087a54e68364cd4bedbe0a8c89520770c

**Comment by fps** [comment]
Oh, the syntax is defined in asciichanges.pegjs. That should give you some hints. I'll maybe add some examples later though.. Thanks again!
